### ISSUE TITLE
Unexpected but possibly intentional behavior with `OffsetNum`

### ISSUE THREAD

**Issue by kyp44** [gjf2a/bare_metal_modulo#10]
Hi, finding this crate very useful, but I discovered an unexpected, or non-intuitive behavior with the way `OffsetNum` arithmetic works. Consider the following:
```rust
let x = OffsetNum::new(3, 10, 1);

println!("{:?} {}", x, x.a());
let y = x - 1;
println!("{:?} {}", y, y.a());
```
This results in:
```
OffsetNum { num: 2, modulo: 10, offset: 1 } 3
OffsetNum { num: 2, modulo: 10, offset: 1 } 3
```
whereas I would have expected:
```
OffsetNum { num: 2, modulo: 10, offset: 1 } 3
OffsetNum { num: 1, modulo: 10, offset: 1 } 2
```
That is, I would have expected arithmetic with integers to always be relative regardless of the offset. After some experimentation, it seems that the integer is first being converted to `OffsetNum::new(1, 10, 1)`, which is equivalent to `0` due to the offset so that the subtraction has no effect. It is obvious how I can accomplish what I want, but is this the intended behavior or an oversight due to just simply doing the obvious conversion before the subtraction?

**Comment by kyp44** [comment]
After some further investigation, it seems that this may be a more general problem with the way that subtraction is implemented for `OffsetNum` and `OffsetNumC`. For example, addition and subtraction work in an inconsistent way relative to each other. Consider:
```rust
let x = OffsetNum::new(5, 9, 1);
let one = OffsetNum::new(1, 9, 1);

let y = x + one;
let z = x - one;
println!("{:?} {}", x, x.a());
println!("{:?} {}", y, y.a());
println!("{:?} {}", z, z.a());
```
This results in:
```
OffsetNumC { num: 4 } 5
OffsetNumC { num: 5 } 6
OffsetNumC { num: 4 } 5
```
That is, addition by one does increment as expected but subtraction does not decrement. The results are the same if `OffsetNumC` is used instead.

**Comment by gjf2a** [comment]
Thanks @kyp44 for opening this issue! I appreciate it. This is certainly unintended behavior. I'm going to take a look at it and fix it up in the next day or so.

**Comment by gjf2a** [comment]
Thanks @kyp44 again for identifying the bug and giving such helpful feedback. I have fixed the bug and added some additional documentation tests to discuss how this works. Let me know if this works for you. Thanks!
